
# SEO settings
title: "writestuffdown.org"
title2: "space" # default: ""
description: "A Place to Write Stuff Down"
keywords: "write, stuff, down"
url: http://writestuffdown.org # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/n7b1w/writestuffdown.github.io
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "The Dude"
  job      : "Dude"
  bio      : "Your not wrong, your just an Asshole."
  thumb    : /images/author.jpg
  email    : snowcrash@protonmail.ch
  url      : http://github.com/n7b1w/writestuffdown.github.io
  github   : http://github.com/n7b1w/writestuffdown.github.io
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
